// <auto-generated>
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.Logging.SetMinimumLevel(LogLevel.Debug);
builder.Logging.AddFilter(FilterUseless);

bool FilterUseless(string s, string c, LogLevel l)
{
    var result = !c?.Contains("Microsoft.AspNetCore.Components.RenderTree") ?? true;
    return result;
}

await builder.Build().RunAsync();