// <copyright file="Program.cs" company="UofU-CS3500">
// Copyright (c) 2024 UofU-CS3500. All rights reserved.
// </copyright>
// <summary>
// Author:    Chase Hammond
// Partner:   Teagan Smith
// Date:      12/5/24
// Course:    CS 3500, University of Utah, School of Computing
// Copyright: CS 3500 and Chase Hammond - This work may not be
//            copied for use in Academic Coursework.
//
// I, Chase, certify that I wrote this code from scratch and
// did not copy it in part or whole from another source.  All
// references used in the completion of the assignments are cited
// in my README file.
//
// File Contents
//
//    This File contains an HTML server that connects to a database
//    containing the game and player information for the snake game.
// </summary>
using CS3500.Networking;
using Microsoft.Extensions.Logging.Abstractions;
using System.Net.NetworkInformation;
using System.Reflection;
using CS3500.DBModels;
using Microsoft.IdentityModel.Tokens;
using System.IO;
Console.WriteLine("Hello, Server!");
NetworkConnection server = new(NullLogger.Instance);

string bodyString = string.Empty;
string tableString = string.Empty;

Server.StartServer(HandleConnection, 12000);

/// <summary>
/// Handles the connection, filtering the requests from the different requests from the browser.
/// </summary>
/// <param name="connection">The network connection.</param>
/// <returns></returns>
void HandleConnection(NetworkConnection connection)
{
    Console.WriteLine("Someone wants to talk");
    string line = connection.ReadLine();
    Console.WriteLine($"Their request: {line}");

    var tokens = line.Split();
    string userPath = tokens[1];

    if (userPath.Contains("/games?gid="))
    {
        string RequestID = userPath.Split('=')[1];
        if (int.TryParse(RequestID, out int GameID))
        {
            bodyString = GeneratePlayersTable(GameID);
        }
    }
    else if (userPath.Contains("/games"))
    {
        bodyString = GenerateGamesTable();
    }
    else if (userPath.Contains("/favicon"))
    {
        ServerFaviconRequest(connection);
    }
    else
    {
        string implementationString =
            "This Project has been updated to use our previously created Snake Game Client as well as our networking class previously built\r\nto create a server where we can host a website to display our captured records from the snake game. As our Snake game connects to\r\na database, it stores the following information\r\nFor Games:\r\n\t- GameID (Generated by DB Table)\r\n\t- Start Time\r\n\t- End Time of Game\r\n\r\nFor Players:\r\n\t- A Player ID (Per Game)\r\n\t- A Game ID (to Link to the specific game)\r\n\t- Max Score\r\n\t- Enter Time\r\n\t- Leave Time\r\n\r\nThis can also correctly handle multiple clients (or tabs open) due to a flag that sets the first person that joins as the \"master\"\r\nsnake. If they were to disconnect early, there are complexities that arise, but also we wouldn't have to deal with such complexities\r\nif the DB Connection was built into the Server.";

        bodyString = """
                     <!DOCTYPE html>
                        <html lang=\en\">
                            <head>
                                <meta charset=\"UTF-8\">
                                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
                                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
                                <title>Welcome Page</title>
                            </head>
                            <body>
                                <div class="container d-flex flex-column justify-content-center align-items-center vh-100">
                                    <h1 class="mb-4 text-center">Welcome to the Game Hub!</h1>
                                    <p class="mb-4 text-center">Explore and track your favorite games with ease.</p>
                                    <a href="/games" class="btn btn-primary btn-lg">Go to Games List</a>
                                    <p>This Project has been updated to use our previously created Snake Game Client as well as our networking class previously built
                     to create a server where we can host a website to display our captured records from the snake game. As our Snake game connects to
                     a database, it stores the following information
                     For Games:
                     	- GameID (Generated by DB Table)
                     	- Start Time
                     	- End Time of Game
                     
                     For Players:
                     	- A Player ID (Per Game)
                     	- A Game ID (to Link to the specific game)
                     	- Max Score
                     	- Enter Time
                     	- Leave Time
                     
                     This can also correctly handle multiple clients (or tabs open) due to a flag that sets the first person that joins as the "master"
                     snake. If they were to disconnect early, there are complexities that arise, but also we wouldn't have to deal with such complexities
                     if the DB Connection was built into the Server. To use this website, please click the buttons and look at the games!</p>
                                </div>
                            </body>
                        </html>
                     """;
    }


    string header = @$"HTTP/1.1 200 OK
                    Date: {DateTime.Now}
                    Content-Type: text/html; charset-UTF-8
                    Content-Length: {bodyString.Length}
                    Connection: keep-alive
                    Server: CS3500_Server

";
    connection.Send(header + bodyString);
}

/// <summary>
/// Generates the games table, connecting to our database and displaying important details.
/// </summary>
/// <returns></returns>
string GenerateGamesTable()
{
    using var db = new AppDbContext();
    var DBGames = db.Games.OrderBy(g => g.GameId).ToList();


    string tableString = string.Empty;

    foreach (var Game in DBGames)
    {
        tableString +=
            "<tr>" +
                $"<td><a href=\"/games?gid={Game.GameId}\" >{Game.GameId}</a></td>" +
                $"<td>{Game.StartTime}</td>" +
                $"<td>{Game.EndTime}</td>" +
            "</tr>";
    }

    string gameBodyString = $@"
    <div class=""container mt-5"">
        <h1 class=""text-center mb-4"">Game List</h1>
        <table class=""table table-bordered table-striped"">
            <thead class=""table-dark"">
                <tr>
                    <th>GameID</th>
                    <th>StartTime</th>
                    <th>EndTime</th>
                </tr>
            </thead>
            <tbody>
                {tableString}
            </tbody>
        </table>
    </div>";

    return WrapHtml("Games", gameBodyString);
}

/// <summary>
/// Servers the favicon request.
/// </summary>
/// <param name="connection">The connection.</param>
/// <returns></returns>
void ServerFaviconRequest(NetworkConnection connection)
{
    string faviconPath = "favicon.ico";

    if (File.Exists(faviconPath))
    {
        byte[] faviconBytes = File.ReadAllBytes(faviconPath);

        // Write HTTP response headers
        connection.Send("HTTP/1.1 200 OK" +
                        "Content-Type: image/x-icon" +
                        $"Content-Length: {faviconBytes.Length}" +
                        "Connection: close");


        // Write the favicon bytes directly to the network stream
        if (faviconBytes != null)
        {
            connection.Send(faviconBytes.ToString());
        }
    }
}

/// <summary>
/// Generates the players table for each given unique Game ID
/// </summary>
/// <param name="GameID">The game identifier.</param>
/// <returns>HTML Body string to send to the web browser</returns>
string GeneratePlayersTable(int GameID)
{
    using var db = new AppDbContext();
    var DBPlayers = db.Players.Where(o => o.Game.GameId == GameID).ToList();

    string tableRows = string.Empty;

    var HighScorePlayers = DBPlayers.OrderByDescending(s => s.MaxScore).ToList();

    foreach (var Player in HighScorePlayers)
    {
        tableRows +=
            "<tr>" +
                $"<td>{Player.PlayerId}</td>" +
                $"<td>{Player.SnakeName}</td>" +
                $"<td>{Player.MaxScore}</td>" +
                $"<td>{Player.EnterTime}</td>" +
                $"<td>{Player.LeaveTime}</td>" +
            "</tr>";
    }

    string playerBodyString =
        $@"
    <div class=""position-absolute top-0 start-0 p-3"">
        <a href=""/games"" class=""btn btn-outline-secondary"">Back to Games</a>
    </div>
    <div class=""container mt-5"">
        <h1 class=""text-center mb-4"">Player List Game: {GameID}</h1>
        <table class=""table table-bordered table-striped"" border=""1"">
            <thead class=""table-dark"">
                <tr>
                    <td>Player ID</td><td>Player Name</td><td>Max Score</td><td>Enter Time</td><td>Leave Time</td>
                </tr>
            </thead>
            <tbody>
            {tableRows}
            </tbody>
        </table>
    </div>";

    return WrapHtml($"Players for Game {GameID}", playerBodyString);
}

/// <summary>
/// Wraps the HTML.
/// </summary>
/// <param name="title">The title.</param>
/// <param name="bodyContent">Content of the body.</param>
/// <returns></returns>
string WrapHtml(string title, string bodyContent)
{
    return $@"
<!DOCTYPE html>
<html lang=""en"">
<head>
    <meta charset=""UTF-8"">
    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">
    <title>{title}</title>
    <link href=""https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"" rel=""stylesheet"">
</head>
<body>
        {bodyContent}
    <script src=""https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js""></script>
</body>
</html>";
}
